export const ALL_MODULES = [
  'AUTH',
  'COMPANIES',
  'FILES',
  'JOBS',
  'PERMISSIONS',
  'RESUMES',
  'ROLES',
  'CUSTOMER_APPROVALS',
  'USERS',
  'SUBSCRIBERS',
  'NOTIFICATIONS',
  'CLIENT',
  'STATISTICS',
  'SKILLS',
  'SUBSCRIPTION_PACKAGE',
  'VIP_HISTORY',
  'TRANSACTIONS',
  'MESSAGES',
]

export const ALL_METHODS = ['GET', 'POST', 'PATCH', 'PUT', 'DELETE', 'HEAD', 'OPTIONS']
